[project]
name = "prompty"
dynamic = ["version"]
description = "Prompty is a new asset class and format for LLM prompts that aims to provide observability, understandability, and portability for developers. It includes spec, tooling, and a runtime. This Prompty runtime supports Python"
authors = [
    {name = "Seth Juarez", email = "seth.juarez@microsoft.com"},
]
dependencies = [
    "pyyaml>=6.0.1",
    "pydantic>=2.8.2",
    "jinja2>=3.1.4",
    "openai>=1.35.10",
    "azure-identity>=1.17.1",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.2.2",
]

[tool.pdm.version]
source = "scm"
fallback_version = "0.1.0"
tag_filter = "python/*"
tag_regex = '^python/(?:\D*)?(?P<version>([1-9][0-9]*!)?(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*((a|b|c|rc)(0|[1-9][0-9]*))?(\.post(0|[1-9][0-9]*))?(\.dev(0|[1-9][0-9]*))?$)$'
write_to = "prompty/_version.py"
write_template = "__version__ = '{}'"