name: prompty JavaScript build and publish

on:
  push:
    paths:
      - "runtime/promptyjs/**"

  workflow_dispatch:
  workflow_call:

jobs:
  prompty-tests:
    name: run unit tests on supported Node.js versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["16.x", "20.x"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Node.js install dependencies
        working-directory: ./runtime/promptyjs
        run: npm install

      - name: Node.js build
        working-directory: ./runtime/promptyjs
        run: npm run build

      - name: Node.js test
        working-directory: ./runtime/promptyjs
        run: npm run test

  publish-artifacts:
    name: publish artifacts
    needs: prompty-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Ensure latest npm
        run: npm install -g npm@latest
      - name: Node.js install dependencies
        working-directory: ./runtime/promptyjs
        run: npm ci
      - name: Node.js build
        working-directory: ./runtime/promptyjs
        run: npm run build --if-present
      - name: Publish package
        working-directory: ./runtime/promptyjs
        run: npm publish --provenance --access public
